# Generated by Django 5.2.7 on 2025-11-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('satuan', models.CharField(max_length=20)),
                ('tanggal_masuk', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
