# Generated by Django 5.2.7 on 2025-11-01 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('jenis', models.CharField(choices=[('masuk', 'Masuk'), ('keluar', 'Keluar')], max_length=10)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gudang.barang')),
            ],
        ),
    ]
